---
git:
  branch: main
triggers:
  cron: "@daily"
clean_workspace: true
builders:
  - docker
docker_name: jenkins/testautomation-agent
docker_tags:
  - "sunet-test-agent-1"
  - "latest"
docker_no_cache: true